# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Regula < Formula
  desc "Evaluate infrastructure as code for security and compliance"
  homepage "https://regula.dev"
  version "1.0.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/fugue/regula/releases/download/v1.0.0/regula_1.0.0_macOS_x86_64.tar.gz"
    sha256 "f3871e6d0431fcc48836356047f2de55b5ab9df5850a6bd33ea9e2e1c530816f"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/fugue/regula/releases/download/v1.0.0/regula_1.0.0_macOS_arm64.tar.gz"
    sha256 "614468e9ee1b34dd57e55f5cad41482cf7a5e7d59dcc16f85aa0f8f132bf5698"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/fugue/regula/releases/download/v1.0.0/regula_1.0.0_Linux_x86_64.tar.gz"
    sha256 "cf6a75b4c47801fa3640957d6b1947cdccce6eb6370b39084f310222852da68b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/fugue/regula/releases/download/v1.0.0/regula_1.0.0_Linux_arm64.tar.gz"
    sha256 "ffb10badc4e2eb161746b17ba332dcafec16d9e68a9d9d4f02d5d224bcbdbaf0"
  end

  def install
    bin.install "regula"
  end
end
